### ISSUE TITLE
Using this on oneAPI Cloud

### ISSUE THREAD

**Issue by tonyreina** [intel/torch-ccl#9]
Is there a way to run this on oneAPI DevCloud?

I've been trying to use PyTorch 1.6 from the Conda install.  Here is the error. It looks like it is trying to find Intel SYCL. I think that should already been in the oneAPI DevCloud environment.

```
(base) u49918@s001-n001:~$ conda activate tony_torch1
(tony_torch1) u49918@s001-n001:~$ conda install pytorch torchvision cpuonly -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/u49918/.conda/envs/tony_torch1

  added / updated specs:
    - cpuonly
    - pytorch
    - torchvision


The following NEW packages will be INSTALLED:

  blas               conda_channel/linux-64::blas-1.0-mkl
  cpuonly            pytorch/noarch::cpuonly-1.0-0
  freetype           conda_channel/linux-64::freetype-2.10.2-h17b3f18_1
  icc_rt             conda_channel/linux-64::icc_rt-2021.1b9-intel_2198
  intel-openmp       conda_channel/linux-64::intel-openmp-2021.1b9-intel_2198
  jpeg               conda_channel/linux-64::jpeg-9b-h024ee3a_2
  libpng             conda_channel/linux-64::libpng-1.6.37-h17b3f18_5
  libtiff            conda_channel/linux-64::libtiff-4.1.0-h2733197_1
  lz4-c              conda_channel/linux-64::lz4-c-1.9.2-h7708b8d_3
  mkl                conda_channel/linux-64::mkl-2021.1b9-intel_2089
  mkl-service        conda_channel/linux-64::mkl-service-2.3.0-py37hd91a846_6
  mkl_fft            conda_channel/linux-64::mkl_fft-1.1.0-py37h3bd38ee_5
  mkl_random         conda_channel/linux-64::mkl_random-1.1.1-py37h873b8bb_6
  ninja              conda_channel/linux-64::ninja-1.9.0-py37hfd86e86_0
  numpy              conda_channel/linux-64::numpy-1.18.5-py37h3f4da41_8
  numpy-base         conda_channel/linux-64::numpy-base-1.18.5-py37h0a9744e_8
  olefile            conda_channel/linux-64::olefile-0.46-py37_0
  pillow             conda_channel/linux-64::pillow-7.1.2-py37hb39fc2d_0
  pytorch            pytorch/linux-64::pytorch-1.6.0-py3.7_cpu_0
  six                conda_channel/linux-64::six-1.15.0-py37h240e974_1
  tbb                conda_channel/linux-64::tbb-2021.1b9-intel_2193
  tbb4py             conda_channel/linux-64::tbb4py-2021.1b9-py37_intel_2193
  torchvision        pytorch/linux-64::torchvision-0.7.0-py37_cpu
  zstd               conda_channel/linux-64::zstd-1.4.4-hdb51d2f_8


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(tony_torch1) u49918@s001-n001:~$ python
Python 3.7.7 (default, Aug 14 2020, 17:11:05) 
[GCC 7.3.0] :: Intel(R) Corporation on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import torch
>>> exit()
(tony_torch1) u49918@s001-n001:~$ git clone https://github.com/intel/torch-ccl.git && cd torch-ccl 
Cloning into 'torch-ccl'...
remote: Enumerating objects: 453, done.
remote: Total 453 (delta 0), reused 0 (delta 0), pack-reused 453
Receiving objects: 100% (453/453), 110.41 KiB | 796.00 KiB/s, done.
Resolving deltas: 100% (231/231), done.
(tony_torch1) u49918@s001-n001:~/torch-ccl$  git checkout  remotes/origin/ccl_torch1.6 -b ccl_torch1.6
Branch 'ccl_torch1.6' set up to track remote branch 'ccl_torch1.6' from 'origin'.
Switched to a new branch 'ccl_torch1.6'
(tony_torch1) u49918@s001-n001:~/torch-ccl$  git submodule sync 
(tony_torch1) u49918@s001-n001:~/torch-ccl$  git submodule update --init --recursive 
Submodule 'third_party/oneCCL' (https://github.com/oneapi-src/oneCCL.git) registered for path 'third_party/oneCCL'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/pybind11'
Cloning into '/home/u49918/torch-ccl/third_party/oneCCL'...
Cloning into '/home/u49918/torch-ccl/third_party/pybind11'...
Submodule path 'third_party/oneCCL': checked out '77ce24f83209072654c4fcd804125f84fed6be32'
Submodule path 'third_party/pybind11': checked out '3e448c0b5e3abcd179781dd718df2bd2340ddb06'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3.git) registered for path 'third_party/pybind11/tools/clang'
Cloning into '/home/u49918/torch-ccl/third_party/pybind11/tools/clang'...
Submodule path 'third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
(tony_torch1) u49918@s001-n001:~/torch-ccl$  python setup.py install
running install
running bdist_egg
running egg_info
creating torch_ccl.egg-info
writing torch_ccl.egg-info/PKG-INFO
writing dependency_links to torch_ccl.egg-info/dependency_links.txt
writing top-level names to torch_ccl.egg-info/top_level.txt
writing manifest file 'torch_ccl.egg-info/SOURCES.txt'
reading manifest file 'torch_ccl.egg-info/SOURCES.txt'
writing manifest file 'torch_ccl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/ccl
copying ccl/__init__.py -> build/lib.linux-x86_64-3.7/ccl
running build_ext
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installation directory: /home/u49918/torch-ccl/ccl
-- Build type: release
-- C compiler : /usr/bin/cc
-- CXX compiler : /usr/bin/c++
-- BFP16 compiler: yes
-- BFP16 AVX512BF compiler: no
-- BFP16 target attributes: yes
-- CCL_INC_DIRS: /home/u49918/torch-ccl/third_party/oneCCL/include;/home/u49918/torch-ccl/third_party/oneCCL/src
-- CCL_ROOT: /glob/development-tools/versions/oneapi/beta09/inteloneapi/ccl/2021.1-beta09
-- CCL_CONFIGURATION: cpu_gpu_dpcpp
-- Found PythonInterp: /home/u49918/.conda/envs/tony_torch1/bin/python (found version "3.7.7") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
Search Compute Runtime by MODULES_PATH: /glob/development-tools/versions/oneapi/beta09/inteloneapi/ccl/2021.1-beta09/lib;/home/u49918/torch-ccl/third_party/oneCCL/cmake
COMPUTE_RUNTIME=dpcpp requested. Using DPC++ provider
DPCPP_ROOT prefix path hint is not defiend
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
Not OpenCL or L0
-- Performing Test INTEL_SYCL_SUPPORTED
-- Performing Test INTEL_SYCL_SUPPORTED - Failed
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find IntelSYCL (missing: INTEL_SYCL_LIBRARIES
  INTEL_SYCL_INCLUDE_DIRS INTEL_SYCL_SUPPORTED)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  third_party/oneCCL/cmake/FindIntelSYCL.cmake:75 (find_package_handle_standard_args)
  third_party/oneCCL/cmake/helpers.cmake:77 (find_package)
  third_party/oneCCL/tests/functional/CMakeLists.txt:62 (activate_compute_runtime)


-- Configuring incomplete, errors occurred!
See also "/home/u49918/torch-ccl/build/CMakeFiles/CMakeOutput.log".
See also "/home/u49918/torch-ccl/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    cmdclass=cmdclass,
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 175, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 161, in call_command
    self.run_command(cmdname)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 54, in run
    self.build_extension(ext)
  File "setup.py", line 76, in build_extension
    cwd=ext.build_dir, env=env)
  File "/home/u49918/.conda/envs/tony_torch1/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '/home/u49918/torch-ccl', '-DPYTORCH_INSTALL_DIR=/home/u49918/.conda/envs/tony_torch1/lib/python3.7/site-packages/torch', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=../ccl', '-DPYTHON_EXECUTABLE=/home/u49918/.conda/envs/tony_torch1/bin/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/u49918/torch-ccl/build/lib.linux-x86_64-3.7']' returned non-zero exit status 1.
(tony_torch1) u49918@s001-n001:~/torch-ccl$ 
```

**Comment by chengjunlu** [comment]
@tonyreina 
We haven't tried to build the torch_ccl with oneAPI DevCloud yet.

It will be enabled later when torch_ccl supports the SYCL backend.
